### ISSUE TITLE
download the dataset

### ISSUE THREAD

**Issue by YongzhengCui** [3dlg-hcvc/rrr#1]
Hello,
Thanks for your work, when I reproduced your work, I encountered some problems about downloading the dataset.When I download the dataset using the following command, I get 404 not found.
`wget -O 3_ON_REAL_train.zip "https://aspis.cmpt.sfu.ca/projects/multion-challenge/2022/challenge/dataset/3_ON_REAL_train"`

**Comment by YongzhengCui** [comment]
When I download the pretrained model, I also get 404 not found.

**Comment by sonia-raychaudhuri** [comment]
Hi. Thanks for your interest in our work. I have fixed the dataset path. You should be able to download it now. For the pretrained models, please try with the updated file paths in the README. Let me know if you face any other issues.

**Comment by sonia-raychaudhuri** [comment]
I am assuming this is fixed now.
